# Griffith local file provider configuration.
#ddev-generated

# This will pull a database dump as provided (and named) by Griffith.
# The dump must be placed in the project root and follow the naming pattern:
# griffith-DD-MM-YYYY-TIME.mysql.bz2
#
# Examples:
# - griffith-06-09-2024-0700.mysql.bz2
# - griffith-04-11-2024-0700.mysql.bz2
#
# The script will identify and import the latest DB dump.

db_import_command:
  command: |
    set -eu -o pipefail
    # set -x
    # List of database dump files
    files=(griffith-*.mysql.bz2)
    # Find the latest dump file by sorting day-month-year format
    latest_dump=$(printf "%s\n" "${files[@]}" | sort -t- -k4,4nr -k3,3nr -k2,2nr | head -n 1)
    echo "The latest DB dump file is: $latest_dump"
    ddev import-db --file=$latest_dump
  service: host
