#!/usr/bin/env bash
#ddev-generated
#annertech-ddev

## Description: Export config from the current Drupal project.
## Usage: cex
## Example: "ddev cex"
## ProjectTypes: drupal,drupal10, drupal11

ddev drush cex -y
