#!/usr/bin/env bash
#ddev-generated
#annertech-ddev

## Description: Rebuild caches for the current Drupal project.
## Usage: cr
## Example: "ddev cr"
## ProjectTypes: drupal,drupal10, drupal11

ddev drush cr
