#!/usr/bin/env bash
#ddev-generated
#annertech-ddev

## Description: Quickly open the current issue you are working on
## Usage: open-issue
## Example: "ddev open-issue"
## Installed globally

DOMAIN="${TEAMWORK_DOMAIN}"

if [[ -z "$DOMAIN" ]]; then
  echo "Error: TEAMWORK_DOMAIN environment variable must be set."
  exit 1
fi

# Get the name of the active Git branch
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Extract the task ID using regex
if [[ $branch_name =~ T-([0-9]+) ]]; then
    task_id="${BASH_REMATCH[1]}"
    result="https://${DOMAIN}/app/tasks/$task_id"

    # Copy to clipboard based on OS
    if command -v xclip &> /dev/null; then
        echo "$result" | xclip -selection clipboard
        echo "Copied to clipboard: $result"
    elif command -v pbcopy &> /dev/null; then
        echo "$result" | pbcopy
        echo "Copied to clipboard: $result"
    else
        echo "Clipboard command not found. Please install xclip (Linux) or use pbcopy (macOS)."
        # Display the result for manual copying
        printf "$result"
        printf "\n\n"
    fi
    case $OSTYPE in
      linux-gnu)
        xdg-open ${result}
        ;;
      "darwin"*)
        open ${result}
        ;;
      "win*"* | "msys"*)
        start ${result}
        ;;
    esac

else
    echo "No task ID found in the branch name."
fi

