#!/usr/bin/env bash
#ddev-generated
#annertech-ddev

## Description: Drush ULI in any Platform.sh project
## Usage: platform-ulitool
## Example: "ddev platform-ulitool"

# @todo: Fail nicely if fzf is not installed

# Colours
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

# Get the project list
echo-green "Start typing to select a project"
PSH_PROJECT=$(ddev exec platform project:list --no-header --columns=id,title --format=tsv --count=0 | fzf --reverse --height=50% --header='id              Project' -1)

# Check if anything was selected
if [[ -z ${PSH_PROJECT} ]]
then
    echo-red "Nothing selected... Exiting"
else
    # Prepare the variables
    PSH_PROJECT_ID=$(echo "${PSH_PROJECT}" | cut -d$'\t' -f1)
    PSH_PROJECT_NAME=$(echo "${PSH_PROJECT}" | cut -d$'\t' -f2)

    # Give a little update on progress
    echo-green "${PSH_PROJECT_NAME} Selected"
    echo-yellow "Getting URL..."

    # Take the selected item and run the platform command.
    ddev exec platform --project="${PSH_PROJECT_ID}" drush uli
fi
