#!/usr/bin/env bash
#ddev-generated

## Description: Get latest DB from live site
## Usage: remote-db
## Example: "ddev remote-db --skip-hooks"

if [ -f "${DDEV_APPROOT}/.ddev/.env" ]; then
    set -a
    source "${DDEV_APPROOT}/.ddev/.env"
    set +a
    if [[ $DDEV_UPSTREAM_PROVIDER ]]; then
        ddev pull $DDEV_UPSTREAM_PROVIDER --skip-files -y $@
    else
	echo "Couldn't identify provider, please use 'ddev pull' manually."
    fi
else
    echo "Couldn't identify provider, please use 'ddev pull' manually."
fi
