#!/usr/bin/env bash
#ddev-generated
#annertech-ddev

## Description: Get latest DB from live site
## Usage: remote-db
## Example: "ddev remote-db --skip-hooks"

fail_msg="Couldn't identify provider, please set it with 'ddev dotenv set .ddev/.env.anner --ddev-upstream-provider [upsun|tibus|etc]' or use 'ddev pull' manually."

if [ -f "${DDEV_APPROOT}/.ddev/.env.anner" ]; then
    set -a
    source "${DDEV_APPROOT}/.ddev/.env.anner"
    set +a
    if [[ $DDEV_UPSTREAM_PROVIDER ]]; then
        ddev pull $DDEV_UPSTREAM_PROVIDER --skip-files -y $@
    else
      echo $fail_msg
    fi
else
    echo $fail_msg
fi
