#!/usr/bin/env bash
#ddev-generated

## Description: Start time tracking on timewarrior
## Usage: timewarrior
## Example: "ddev timewarrior"

#!/bin/bash

# Get the name of the active Git branch
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Extract the task ID using regex
if [[ $branch_name =~ T-([0-9]+) ]]; then
    task_id="${BASH_REMATCH[1]}"
    url="https://projects.annertech.com/app/tasks/$task_id"
    project=`basename "$PWD"`

    if command -v timew &> /dev/null; then
	timew start $url $project
    else
        echo "timew not found"
    fi
else
    echo "No task ID found in the branch name."
fi

