#!/usr/bin/env bash
#ddev-generated
#annertech-ddev

## Description: Tag current timewarrior activity
## Usage: timew
## Example: "ddev timew"
## Installed globally

DOMAIN="${TEAMWORK_DOMAIN}"

if [[ -z "$DOMAIN" ]]; then
  echo "Error: TEAMWORK_DOMAIN environment variable must be set."
  exit 1
fi

# Get the name of the active Git branch
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Extract the task ID using regex
if [[ $branch_name =~ T-([0-9]+) ]]; then
    task_id="${BASH_REMATCH[1]}"
    result="https://${DOMAIN}/app/tasks/$task_id"

    # Copy to clipboard based on OS
    if command -v timew &> /dev/null; then
        basename=$(basename "$PWD")
        timew tag $result $basename
    else
	      echo "timewarrior (timew) is not installed"
    fi

else
    echo "No task ID found in the branch name."
fi

