#!/usr/bin/env bash
#ddev-generated
#annertech-ddev

## Description: Check for updates of the annertech-ddev addon
## Usage: check-annertech-ddev [flags] [args]
## Example: "ddev check-annertech-ddev"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color
STARS='****************************************'

# Get the current Addon version
ADDONVER=$(grep -oP "^version:\s*\K.*" .ddev/addon-metadata/annertech-ddev/manifest.yaml)

# Define the path to store the version file
VERSION_FILE="/tmp/annertech-ddev-addon-version.txt"

# Function to get the latest tag from GitHub API using curl and jq
get_latest_tag() {
    # Use -s for silent mode, L for follow redirects, and output in JSON format
    # Extract the tag_name field using jq and convert it to a raw string (without quotes)
    curl -sL https://api.github.com/repos/annertech/annertech-ddev/releases/latest | \
        jq -r ".tag_name"
}

# Check if version file exists
if [ ! -f "$VERSION_FILE" ]; then
    echo "Version file does not exist. Creating..."
    # Get latest tag and save it to the version file
    get_latest_tag > "$VERSION_FILE"
else
    # Calculate how long ago the version file was modified in seconds
    age=$(( $(date +%s) - $(stat -c %Y "$VERSION_FILE") ))

    if [ $age -gt 86400 ]; then
        echo "Version file is older than 24 hours. Updating..."
        # Get latest tag and save it to the version file
        get_latest_tag > "$VERSION_FILE"
    else
        echo "Version file exists and is less than 24 hours old."
    fi
fi

LATESTVER=$(cat ${VERSION_FILE})


printf "%b\n" "${YELLOW}${STARS}"
printf "Checking Annertech DDEV addon\n"
printf "Installed version: %s\n" "${ADDONVER}"
printf "Latest version: %b\n" "${LATESTVER}${NC}"

if [ "$(printf '%s\n' "${LATESTVER}" "${ADDONVER}" | sort -V | head -n1)" = "${LATESTVER}" ]; then
  printf "%b\n" "${GREEN}${STARS}"
  printf "Annertech Add-on: Up to date\n"
  printf "%b\n" "${STARS}${NC}"
else
  printf "%b\n" "${RED}${STARS}"
  printf "Annertech Add-on: Update required!\n"
  printf "Please run:\n"
  printf "ddev add-on get annertech/annertech-ddev\n"
  printf "%b\n" "${STARS}${NC}"
fi
