#ddev-generated
#annertech-ddev
# Sitemap URLs render as http://default when simple_sitemap has no base_url
# and the sitemap is generated by cron/drush (see issue #182).
SITEMAP_SETTINGS="$APPROOT/config/sync/simple_sitemap.settings.yml"
if [[ -n "$EXT_FILE" ]] && strip_yaml "$EXT_FILE" | grep -qE "^\s+simple_sitemap:"; then
  if [[ ! -f "$SITEMAP_SETTINGS" ]]; then
    warn "simple_sitemap is enabled but config/sync/simple_sitemap.settings.yml not found"
  else
    SITEMAP_BASE_URL=$(strip_yaml "$SITEMAP_SETTINGS" | sed -nE "s/^base_url:[[:space:]]*['\"]?([^'\"]*)['\"]?[[:space:]]*$/\1/p" | head -1)
    if [[ -z "$SITEMAP_BASE_URL" ]]; then
      critical_fail "simple_sitemap base_url is empty, sitemap.xml URLs may render as http://default"
    elif ! [[ "$SITEMAP_BASE_URL" =~ ^https?://[^/]+\.[^/]+ ]] || [[ "$SITEMAP_BASE_URL" =~ ^https?://(default|localhost|.*\.ddev\.site)(/|:|$) ]]; then
      critical_fail "simple_sitemap base_url '$SITEMAP_BASE_URL' is not a valid production domain"
    else
      pass "simple_sitemap base_url is set ($SITEMAP_BASE_URL)"
    fi
  fi
fi
